analyzer:
  exclude:
    - "build/**"
    - ".dart_tool/**"
    - "ios/**"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - always_declare_return_types
