# Es el puente obligatorio para que CocoaPods entienda los métodos de Flutter
init_settings_path = File.expand_path(File.join('..', '.flutter-plugins-dependencies'), __FILE__)
if File.exist?(init_settings_path)
  require init_settings_path
end

# Forzamos el despliegue mínimo global a iOS 15.0
platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Método correcto para inyectar los plugins locales de Flutter
  flutter_ios_podfile_setup
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
