name: Flutter CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK paths
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Create Production Environment File
        env:
          URL_SECRET: ${{ secrets.SUPABASE_URL }}
          KEY_SECRET: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "SUPABASE_URL=${URL_SECRET}" > .env
          echo "SUPABASE_ANON_KEY=${KEY_SECRET}" >> .env
          echo "SUPABASE_URL=${URL_SECRET}" > .env.production
          echo "SUPABASE_ANON_KEY=${KEY_SECRET}" >> .env.production

      - name: Decode Android Keystore File
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode --ignore-garbage > android/app/upload-keystore.jks

      - name: Create Sign Properties File
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Run flutter analyze
        run: flutter analyze lib/

      - name: Build Web Production Release
        run: flutter build web --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trueke-production-release
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/web/
