name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_sign_android:
    name: Compilar y Firmar Android App Bundle - Producción
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Entorno Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar Dependencias del Proyecto
        run: flutter pub get

      - name: Generar Mock de variables de entorno para CI
        run: touch .env

      - name: Preparar y Decodificar Keystore de Produccion
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Compilar Android App Bundle (.aab) con Auto-Incremento y Firma Nativa
        run: |
          flutter build appbundle --release --build-number=$GITHUB_RUN_NUMBER
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Almacenar Bundle de Produccion Compilado (.aab)
        uses: actions/upload-artifact@v4
        with:
          name: trueke-production-bundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7
